#+TITLE: Holo Fuel UI
#+STARTUP: org-startup-with-inline-images inlineimages
#+OPTIONS: ^:nil # Disable sub/superscripting with bare _; _{...} still works
#+LATEX_HEADER: \usepackage[margin=1.0in]{geometry}

* Holo Fuel User Interface

Displays the Agent's account Nickname and Agent ID, and available balance (credit and balance, net
of payables such as fees and outstanding funds promised but not yet received by the recipient).

** Dashboard

Pending operations and current Transaction are the primary display.  In the menu button, navigation
to the Send and Request funds pages can be found.

* Running the hApp

** Requirements

   Check out and build [[https://github.com/Holo-Host/holofuel.git][holofuel]] and [[https://github.com/holochain/n3h][n3h]] in your =~/src/= directory.  First, build =n3h=:

   #+BEGIN_EXAMPLE bash
   $ cd ~/src
   $ git clone git@github.com/holochain/n3h.git -b master
   $ cd n3h
   $ npm install
   #+END_EXAMPLE

   Next, build the HoloFuel DNA package =~/src/holofuel/dist/holofuel.dna.json=:

   #+BEGIN_EXAMPLE bash
   $ cd ~/src
   $ git clone git@github.com/Holo-Host/holofuel.git -b develop
   $ make -C holofuel build install
   #+END_EXAMPLE

** Building

   Obtain the =holofuel-app=, and Compile the project resources with =webpack=:

   #+BEGIN_EXAMPLE bash
   $ git clone git@github.com/mjbrisebois/holofuel-app.git
   $ cd holofuel-app
   $ npm run build
   #+END_EXAMPLE


** Starting DNA Agents

   Run a "bootstrap" DNA agent:
   #+BEGIN_EXAMPLE bash
   $ cd ~/src/holofuel-app
   $ make start-bootstrap-agent-dna
   #+END_EXAMPLE

   This creates a file in your ~/src/holofuel directory, used to start subsequent DNA agents
   connected via the "bootstrap" agent.  In other tabs/windows, run:

   #+BEGIN_EXAMPLE bash
   $ cd ~/src/holofuel-app
   $ make start-bootstrap-dna-1
   #+END_EXAMPLE

   And, in another tab/window (if desired):

   #+BEGIN_EXAMPLE bash
   $ cd ~/src/holofuel-app
   $ make start-bootstrap-dna-2
   #+END_EXAMPLE

** Running the =holofuel-app= GUI

   Run a simple HTTP server in the root directory, to make available the
   =~/src/holofuel-app/index.html= file at by navigating to [[http://localhost:8000]] with a web
   browser:

   #+BEGIN_EXAMPLE bash
   $ cd ~/src/holofuel-app
   $ python -m SimpleHTTPServer
   #+END_EXAMPLE

   This will redirect you to [[http://localhost:8000/#/3000/]] (note the port 3000, assigned to the first "bootstrap" agent).

   Any subsequent agents you started (above), will be assigned ports starting at 3100,
   eg. [[http://localhost:8000/#/3100/]], [[http://localhost:8000/#/3101/]], ...
